# Generated by Django 5.1.7 on 2025-10-01 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('mp_init_point', models.URLField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mp_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTalla',
            fields=[
                ('idGrupoTalla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Tallas',
                'verbose_name_plural': 'Grupos de Tallas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('stockMinimo', models.IntegerField(default=0)),
                ('stock_talla', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['producto__subcategoria__categoria__nombre', 'producto__subcategoria__nombre', 'producto__nombre', 'talla__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=120, null=True)),
                ('shipping_department', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('importado', 'Importado')], max_length=20)),
                ('productos', models.TextField(help_text='Lista de productos o descripcion')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idROL', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCarrito',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fechaCambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.carrito')),
            ],
            options={
                'verbose_name': 'Estado del Carrito',
                'verbose_name_plural': 'Estados del Carrito',
                'ordering': ['-fechaCambio'],
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral', models.PositiveIntegerField(default=5)),
                ('en_alerta', models.BooleanField(default=False)),
                ('first_detected', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alert', to='BACKEND.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('idmovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('cantidad', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BACKEND.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=64, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=32)),
                ('status_detail', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='COP', max_length=8)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BACKEND.carrito')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BACKEND.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='COP', max_length=8)),
                ('metodo_pago', models.CharField(default='mercadopago', max_length=32)),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('emitida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='emitida', max_length=16)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=120, null=True)),
                ('shipping_department', models.CharField(blank=True, max_length=120, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='BACKEND.pedido')),
            ],
            options={
                'db_table': 'BACKEND_factura',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='BACKEND.producto'),
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BACKEND.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BACKEND.producto')),
            ],
            options={
                'db_table': 'BACKEND_facturaitem',
            },
        ),
        migrations.CreateModel(
            name='SalesRangeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('incluir_aprobados', models.BooleanField(default=True)),
                ('ventas_netas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('items_totales', models.PositiveIntegerField(default=0)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('top_producto_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('top_cantidad', models.PositiveIntegerField(default=0)),
                ('bottom_producto_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('bottom_cantidad', models.PositiveIntegerField(default=0)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('bottom_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='BACKEND.producto')),
                ('top_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='BACKEND.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRangeReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BACKEND.salesrangereport')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idSubcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True)),
                ('stockMinimo', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='BACKEND.categoria')),
                ('grupoTalla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='BACKEND.grupotalla')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='BACKEND.subcategoria'),
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='BACKEND.grupotalla')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BACKEND.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BACKEND.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BACKEND.talla')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='BACKEND.talla'),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('idCarritoItem', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30)),
                ('fechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BACKEND.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BACKEND.talla')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('idtipoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BACKEND.pago')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_topic', models.CharField(max_length=32)),
                ('mp_id', models.CharField(max_length=64)),
                ('raw', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('mp_topic', 'mp_id')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('avatar_seed', models.CharField(blank=True, help_text='Seed para el avatar personalizado', max_length=32, null=True)),
                ('avatar_options', models.JSONField(blank=True, help_text='Opciones JSON del avatar personalizado', null=True)),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='usuarios_set', to='auth.group', verbose_name='grupos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BACKEND.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuarios_set_perm', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('valoracion', models.PositiveSmallIntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_avatar_seed', models.CharField(blank=True, max_length=32, null=True)),
                ('usuario_avatar_options', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BACKEND.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BACKEND.producto')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.AddIndex(
            model_name='salesrangereport',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='BACKEND_sal_fecha_i_829d81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesrangereport',
            unique_together={('fecha_inicio', 'fecha_fin', 'incluir_aprobados')},
        ),
        migrations.AddIndex(
            model_name='salesrangereportitem',
            index=models.Index(fields=['reporte'], name='BACKEND_sal_reporte_fd88de_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrangereportitem',
            index=models.Index(fields=['producto'], name='BACKEND_sal_product_c95054_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesrangereportitem',
            unique_together={('reporte', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('nombre', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='talla',
            unique_together={('nombre', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='pedidoitem',
            unique_together={('pedido', 'producto', 'talla')},
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'talla')},
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('carrito', 'producto', 'talla')},
        ),
    ]
