# Generated by Django 5.2 on 2025-06-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['producto__subcategoria__categoria__nombre', 'producto__subcategoria__nombre', 'producto__nombre', 'talla__nombre']},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='BACKEND.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stockMinimo',
            field=models.IntegerField(default=0),
        ),
    ]
