# Generated by Django 5.1.7 on 2025-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_options',
            field=models.JSONField(blank=True, help_text='Opciones JSON del avatar personalizado', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar_seed',
            field=models.CharField(blank=True, help_text='Seed para el avatar personalizado', max_length=32, null=True),
        ),
    ]
