# Generated by Django 5.1.7 on 2025-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
