# Generated by Django 5.2.1 on 2025-09-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_options',
            field=models.JSONField(blank=True, help_text='Opciones JSON del avatar personalizado', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar_seed',
            field=models.CharField(blank=True, help_text='Seed para el avatar personalizado', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
