# Generated by Django 5.2 on 2025-05-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
    ]
