# Generated by Django 5.2.1 on 2025-09-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockalertactivo',
            name='inventario',
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral', models.PositiveIntegerField(default=5)),
                ('en_alerta', models.BooleanField(default=False)),
                ('first_detected', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alert', to='BACKEND.inventario')),
            ],
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='StockAlertActivo',
        ),
    ]
