# Generated by Django 5.2.1 on 2025-08-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='codigorecuperacion',
            index=models.Index(fields=['usuario', 'creado'], name='BACKEND_cod_usuario_934475_idx'),
        ),
    ]
