# Generated by Django 5.1.7 on 2025-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
