# Generated by Django 5.2 on 2025-06-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_alter_inventario_options_alter_inventario_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.talla'),
        ),
    ]
