# Generated by Django 5.1.7 on 2025-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario_apellido',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_avatar_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_avatar_seed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
