# Generated by Django 5.1.7 on 2025-09-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
