# Generated by Django 5.2.1 on 2025-08-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_codigorecuperacion_backend_cod_usuario_934475_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codigorecuperacion',
            name='BACKEND_cod_usuario_934475_idx',
        ),
    ]
