# Generated by Django 5.2.1 on 2025-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_usuario_avatar_options_usuario_avatar_seed_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={},
        ),
        migrations.AddField(
            model_name='carrito',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='mp_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
