# Generated by Django 5.2.1 on 2025-09-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_pedidoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='factura',
            table='BACKEND_factura',
        ),
    ]
