# Generated by Django 5.1.7 on 2025-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_categoria_inventario_pedido_movimiento_pago_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
