# Generated by Django 5.2.1 on 2025-09-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_comentario_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
    ]
