# Generated by Django 5.1.7 on 2025-05-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_carrito_estadocarrito_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
