# Generated by Django 5.1.7 on 2025-09-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='telefono',
        ),
    ]
