# Generated by Django 5.2 on 2025-06-16 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_alter_inventario_producto_alter_inventario_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='BACKEND.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='BACKEND.talla'),
        ),
    ]
