# Generated by Django 5.1.7 on 2025-09-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0004_remove_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='nombre',
        ),
    ]
