# Generated by Django 5.1.7 on 2025-05-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_remove_proveedor_usuario'),
        ('BACKEND', '0002_subcategoria'),
        ('BACKEND', '0004_producto_stock_alter_producto_imagen'),
    ]

    operations = [
    ]
