# Generated by Django 5.2.1 on 2025-09-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0005_pedido_created_at_pedido_numero_pedido_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='shipping_department',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_department',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
