# Generated by Django 5.1.7 on 2025-09-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0005_remove_direccion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='principal',
        ),
    ]
