# Generated by Django 5.2.1 on 2025-09-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0006_factura_shipping_address_factura_shipping_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.CreateModel(
            name='SalesRangeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('incluir_aprobados', models.BooleanField(default=True)),
                ('ventas_netas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('items_totales', models.PositiveIntegerField(default=0)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('top_producto_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('top_cantidad', models.PositiveIntegerField(default=0)),
                ('bottom_producto_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('bottom_cantidad', models.PositiveIntegerField(default=0)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('bottom_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='BACKEND.producto')),
                ('top_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='BACKEND.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRangeReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BACKEND.salesrangereport')),
            ],
        ),
        migrations.AddIndex(
            model_name='salesrangereport',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='BACKEND_sal_fecha_i_829d81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesrangereport',
            unique_together={('fecha_inicio', 'fecha_fin', 'incluir_aprobados')},
        ),
        migrations.AddIndex(
            model_name='salesrangereportitem',
            index=models.Index(fields=['reporte'], name='BACKEND_sal_reporte_fd88de_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrangereportitem',
            index=models.Index(fields=['producto'], name='BACKEND_sal_product_c95054_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesrangereportitem',
            unique_together={('reporte', 'producto')},
        ),
    ]
