# Generated by Django 5.2.1 on 2025-09-24 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0007_alter_direccion_options_salesrangereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertActivo',
            fields=[
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alerta_activa', serialize=False, to='BACKEND.inventario')),
                ('tipo', models.CharField(choices=[('stock_low', 'Stock bajo'), ('stock_out', 'Sin stock')], max_length=32)),
                ('umbral', models.PositiveIntegerField(default=5)),
                ('cantidad', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('stock_low', 'Stock bajo'), ('stock_out', 'Sin stock')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tipo', 'resuelto'], name='BACKEND_not_tipo_6dcd61_idx')],
            },
        ),
    ]
